{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.12",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.10-SNAPSHOT.jar",
          "url": "fabric-loom-1.10-SNAPSHOT.jar",
          "size": 1041130,
          "sha512": "9257d25704096867579b2b7a4fb58bf34316779ce1e79e128feed071bbbe7c7cf7b6743cf9a96a28a45e748b7c0dbed7e260af2640e2ba40657c8fcbfc3b8dc7",
          "sha256": "d3bd0f10512aacc576e546b01e2dc82bab4a32fc82a0747d3358e5831164da9e",
          "sha1": "e498f0dfa4b186a5db6dd694ad4f2445ab596838",
          "md5": "4e5679372235483fcc69acd5598a936e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.12",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.10-SNAPSHOT.jar",
          "url": "fabric-loom-1.10-SNAPSHOT.jar",
          "size": 1041130,
          "sha512": "9257d25704096867579b2b7a4fb58bf34316779ce1e79e128feed071bbbe7c7cf7b6743cf9a96a28a45e748b7c0dbed7e260af2640e2ba40657c8fcbfc3b8dc7",
          "sha256": "d3bd0f10512aacc576e546b01e2dc82bab4a32fc82a0747d3358e5831164da9e",
          "sha1": "e498f0dfa4b186a5db6dd694ad4f2445ab596838",
          "md5": "4e5679372235483fcc69acd5598a936e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.12",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.10-SNAPSHOT-sources.jar",
          "url": "fabric-loom-1.10-SNAPSHOT-sources.jar",
          "size": 578884,
          "sha512": "450b46e920158f00ac31732924f95d278c421d1e920038b450857975e01cefc54a5878ec8deca19007795601a16ad7c522c9d6f2c07f96b6c8e02860ed40b16e",
          "sha256": "c79bf4ebe9121b40e6202975084c73285976d673fde72f4e6a2a83d2bb453c62",
          "sha1": "4012f98f179c6278512880339e0652aa046548ee",
          "md5": "18fe98ce9a7f527220b2079ac10b014d"
        }
      ]
    }
  ]
}
